name: Issue Autoresponse

on:
  issues:
    types: [opened]

jobs:
  auto-response:
    runs-on: ubuntu-latest

    steps:
    - uses: derekprior/add-autoresponse@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        respondableId: ${{ github.event.issue.node_id }}
        response: "Hello! Thank you for your interest in our project.\nWe use github for visibility, but our issue tracking is done using sourcehut.\nUntil we have it setup to mirror issues to sourcehut, if you could take the time to re-submit the issue there we will be able to repsond to your issue sooner.\nThanks!"
        author: ${{ github.event.issue.user.login }}

  mirror:
    runs-on: ubuntu-latest

    steps:
    - uses: athorp96/sourcehut_issue_mirror@master
      with:
        title: ${{ github.event.issue.user.title }}
        body: ${{ github.event.issue.user.body }}
        submitter: ${{ github.event.issue.user.user.login }}
        tracker-owner: "~whereswaldon"
        tracker-name: "github-action-replication-testing"
        oauth-token: ${{ secrets.SRHT_OAUTH_TOKEN }}
        
